server:
  port: 9528

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment-routes              #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001      #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service  #uri的协议为lb，表示启用Gateway的负载均衡功能。
        predicates:
          - Path=/payment/get/**         #断言，路由相匹配进行路由

      - id: payment-routes2                #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001        #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service   #uri的协议为lb，表示启用Gateway的负载均衡功能。
        predicates:
          - Path=/payment/lb/**           #断言，路由相匹配进行路由
          #- Cookie=username,WD   #带 cookie 的 => curl http://localhost:9528/payment/lb --cookie "username=WD"
          #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式  => curl http://localhost:9528/payment/lb -H "X-Request-ID:123"
          #- Host=**.atguigu.com    #   => curl http://localhost:9528/payment/lb -H "Host:www.atguigu.com"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
