server:
  port: 8006
spring:
  application:
    name: cloud-providerconsul-payment

#consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}