server:
  port: 8801


spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      bindings:   #服务的整合处理
        output:   #通道的名称
          destination: studyExchange  #表示使用RabbitMQ 中 Exchange 的主题名称
          content-type: application/json  #设置消息的类型，为json。文本为“text/plain”
          binder: defaultRabbit   # 设置要绑定的消息服务的具体设置
      binders:  #在此处要绑定的rabbitmq的服务消息
        defaultRabbit:   #表示定义的名称，用于binding的整合
          type: rabbit   #消息组件的类型
          environment:   #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

#eureka注册
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 5  #设置间隔时间
    instance-id: send-8801.com  #在消息列表中显示主机名称
    prefer-ip-address: true    #访问路径变为IP地址
